name: Build Documentation

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Run Dokka
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            dokkaHtmlMultiModule
            --scan
      
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build/dokka/htmlMultiModule
